######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 8 11:29:11 2006
######################################################################

TEMPLATE = subdirs

CONFIG += debug

# Subdirs
SUBDIRS = src
