######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 8 11:28:58 2006
######################################################################

TEMPLATE = app
TARGET = ../bin/bequnge
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
	interpreter.cpp \
	array.cpp

HEADERS += interpreter.h \
	array.h
