######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 8 11:28:58 2006
######################################################################

TEMPLATE = app
TARGET = ../bin/bequnge
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
SOURCES += mainwindow.cpp
SOURCES += interpreter.cpp
SOURCES += array.cpp

HEADERS += mainwindow.h
HEADERS += interpreter.h
HEADERS += array.h

FORMS += mainwindow.ui
